### PR TITLE
disable some part of geanypy-encodings.[ch] which are not part of Gea…

### PR DESCRIPTION
**Pull request by kugel-**
I'll push this to master soon if there're no objections.

### CODE REVIEW

**Comment by b4n** [comment]
Bah, just delete everything, at worse it'll be in the VCS history

**Comment by codebrainz** [comment]
Yeah, rather have the code removed than commented/#if-ed out. Make it easier to review the diff too.

**Comment by kugel-** [comment]
Okay okay :-) Did that

**Comment by codebrainz** [comment]
@kugel- Except for the empty `geanypy-encoding.h` header, it looks OK to me. I haven't tested it yet, but as long as you have and are confident it won't break the build/runtime, it's fine by me if you merge it.

**Pull request merged**
