### PR TITLE
Fix editor.document property

### PR DESCRIPTION
**Pull request by ermshiperete**
Previously editor.document was always None. Also fix a typo.

[Review on Reviewable](https://reviewable.io/reviews/codebrainz/geanypy/39)

### CODE REVIEW

**Comment by b4n** [comment]
Looks sensible

**Comment by kugel-** [comment]
Trying out Reviewable

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/geanypy-editor.c, line 61 \[r1\]](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-K9Vlk1N41aKpA4z7hEV:-K9Vlk1N41aKpA4z7hEW:676834233) ([raw file](https://github.com/codebrainz/geanypy/blob/c26890b4ae99892e780ca9bb51e78b30c0be18b9/src/geanypy-editor.c#L61)):*
LGTM

---

*[src/geanypy-editor.c, line 295 \[r1\]](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-K9VlaBZlBWQXqCprO8z:-K9VlaBZlBWQXqCprO9-:19641765) ([raw file](https://github.com/codebrainz/geanypy/blob/c26890b4ae99892e780ca9bb51e78b30c0be18b9/src/geanypy-editor.c#L295)):*
Should be a separete commit. Can you split up please? (no need for a separate PR, just add the commit)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-:-K9VmBs0d-aDE-QosgZ2:1822114264)*

**Comment by kugel-** [comment]
(need to type text to change blocking status for my comment)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-:-K9Vnlya7S9MMZ2Z1YTA:1695676462)*

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/geanypy-editor.c, line 295 \[r1\]](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-K9VlaBZlBWQXqCprO8z:-K9VodI5OQq4beD28Qqq:-499146009) ([raw file](https://github.com/codebrainz/geanypy/blob/c26890b4ae99892e780ca9bb51e78b30c0be18b9/src/geanypy-editor.c#L295)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codebrainz/geanypy/39)*

**Comment by kugel-** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/geanypy-editor.c, line 295 \[r1\]](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-K9VlaBZlBWQXqCprO8z:-K9VpVIpSG7Clpvp6uqt:-2137399250) ([raw file](https://github.com/codebrainz/geanypy/blob/0301fd3692754442bfdde5226ddc525820e0ba2c/src/geanypy-editor.c#L295)):*
Thanks

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codebrainz/geanypy/39)*

**Comment by kugel-** [comment]
> Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful

A bit misleading. I resolved the discussion with that review.

**Comment by kugel-** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codebrainz/geanypy/39#-:-KCB5O33yVgOoQe9JvGW:1417088721)*

**Comment by elextr** [comment]
@kugel- from my point of view this reviewable thing seems to make a lot of noise for not much value, whats your impression as the actual user?

**Comment by kugel-** [comment]
The reviewable UI definitely offers better review than plain github which is very much welcome. 
Need to check with more complex uses (including force pushing).

**Pull request merged**
