### PR TITLE
unload python plugins when geanypy is deactivated

### PR DESCRIPTION
**Pull request by robblue2x**
This should fix bug #12 
when the geanypy plugin's cleanup is called it closes the python plugin manager and unloads all the python plugins

### CODE REVIEW

**Comment by robblue2x** [comment]
You are completely right, sorry about that, first pull request on github.
I'll fix the leak tonight and ammend the indentation, my editor (set to auto) has used tabs instead of spaces.

**Comment by robblue2x** [comment]
I'll check to see if i can find a possible leak on _CallObject()

**Comment by robblue2x** [comment]
I call Py_DECREF on the result of the PyObject_CallObject, so it shouldn't leak now

**Comment by codebrainz** [comment]
What are all the extra commits/changes about?

**Comment by codebrainz** [comment]
I ask because I want to merge the unloading fix before next release but the PR looks a fair bit more involved since my last comments about the leaks.

**Pull request closed without merging**
