### PR TITLE
Fix for issue #30 unloading all plugins no longer updates the .loaded_plugins file

### PR DESCRIPTION
**Pull request by robblue2x**
fix for #30 removing all python plugins from .loaded_plugins file when geanypy is deactivated

### CODE REVIEW

**Comment by codebrainz** [comment]
Did you test this? This was the very first thing I tried to code myself after pulling in the original fix and it made Geany hang. I could've been doing something stupid I guess.

**Comment by robblue2x** [comment]
Yeah I tested it when I did it, and I double checked there now just to be sure. It works.
Is there any more formal way to test it or anything I can do to provide test results?

**Comment by codebrainz** [comment]
Naw I was just curious because I made nearly identical changes as this, independently, and it didn't work (would freeze when unloading and reloading GeanyPy C plugin via Geany's Plugin Manager dialog).

As Geany 1.25 is being released as we speak, the crasher bug will probably live on until v1.26, then we'll merge the main fix plus this follow-up.

**Comment by robblue2x** [comment]
No probs, I made a few mistakes while dev+testing this, had all the bool's in place, and it didn't work... I'd forgotten to add the 'if' on line 146 :smile:

**Comment by kugel-** [comment]
With #37 geanypy can't be disabled until no sub-plugin depending on it is active anymore. So I guess this PR is kinda moot?

**Pull request closed without merging**
