### PR TITLE
Mark-Up/Down Previewer

### PR DESCRIPTION
**Pull request by xiota**
Semi-real-time preview of multiple light-weight markup languages.

 * Formats supported via `pandoc`:
	- Markdown
	- reStructuredText
	- Txt2tags
	- LaTeX
	- Docbook
 * `asciidoc` support
 * RFC-822-like email-messages processed according to the Content-Type header.
 * Rudimentary web browsing.

### CODE REVIEW

**Comment by codebrainz** [comment]
Nice work. I wonder if it would be better to add it to [Geany-Plugins](https://github.com/geany/geany-plugins) instead, so it's more widely distrubted and used?

**Comment by xiota** [comment]
Submitted it to you because was under the impression that this is upstream for geanypy.  Figured it would eventually make its way to them.  Guess where to put it depends on whether the python scripts should stay together?  Don't have strong opinions about where to put it.  Will put it where ever you recommend.

Do you know if there are any other python-based plugins?  Didn't find any other than the ones included with geanypy.

**Comment by codebrainz** [comment]
It is upstream, but I'm not sure how many plugins we want in the core. I talked to @b4n on IRC about how to add it to the Geany-Plugins build system and he thinks it should be do-able. It requires some changes to Geany-Plugins build system, but it would be nice to have some "first class" Python plugins, IMO.

**Comment by xiota** [comment]
Let me know what you think is best...

**Comment by xiota** [comment]
submitted a pull request for this plugin at geany-plugins: https://github.com/geany/geany-plugins/pull/489

**Pull request closed without merging**
